### ISSUE TITLE
undefined method 'id' for 29:Integer

### ISSUE THREAD

**Issue by mboremski** [xmera-circle/redmine_workload#7]
User with ID 29 seem to lead to an Error for unknown reason:

```
Started GET "/workloads?utf8=%E2%9C%93&workload%5Bfirst_day%5D=2022-06-11&workload%5Blast_day%5D=2022-08-10&workload%5Bstart_date%5D=2022-06-21&workload%5Bgroups%5D%5B%5D=7" for xxx.xxx.xxx.xxx at 2022-06-21 15:46:48 +0200
Processing by WorkloadsController#index as HTML
  Parameters: {"utf8"=>"✓", "workload"=>{"first_day"=>"2022-06-11", "last_day"=>"2022-08-10", "start_date"=>"2022-06-21", "groups"=>["7"]}}
  Current user: boremski (id=10)
Completed 500 Internal Server Error in 341ms (ActiveRecord: 14.1ms)
  
NoMethodError (undefined method `id' for 29:Integer
Did you mean?  i):
  
plugins/redmine_workload/lib/redmine_workload/wl_date_tools.rb:58:in `working_days_in_time_span'
plugins/redmine_workload/app/models/group_workload.rb:75:in `total_availabilities_of'
plugins/redmine_workload/app/models/group_workload.rb:69:in `block in user_workload_with_availabilities'
plugins/redmine_workload/app/models/group_workload.rb:68:in `each'
plugins/redmine_workload/app/models/group_workload.rb:68:in `user_workload_with_availabilities'
plugins/redmine_workload/app/models/group_workload.rb:59:in `sorted_user_workload'
plugins/redmine_workload/app/models/group_workload.rb:50:in `block in define_group_members'
plugins/redmine_workload/app/models/group_workload.rb:49:in `each'
plugins/redmine_workload/app/models/group_workload.rb:49:in `each_with_object'
plugins/redmine_workload/app/models/group_workload.rb:49:in `define_group_members'
plugins/redmine_workload/app/models/group_workload.rb:20:in `initialize'
plugins/redmine_workload/app/controllers/workloads_controller.rb:44:in `new'
plugins/redmine_workload/app/controllers/workloads_controller.rb:44:in `index'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

**Comment by mboremski** [comment]
Thank you.. 👍
